version: '3.9'

services:
  app:
    build: .
    ports:
      - "4444:4444"
    depends_on:
      - postgres
    env_file:
      - '.env'
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - PORT=4444
  postgres:
    image: postgres:17.6-alpine
    ports:
      - "5432:5432"
    volumes:
      - p2p:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=postgres
      - POSTGRES_DB=allure-test-runner

volumes:
  p2p: