tabname: Build docs

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    escsteps:
      - uses: actions/checkout@v3

      - name: Read .nvmrc
        run: echo "NVMRC=$(cat .nvmrc)" >> $GITHUB_ENV

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '${{ env.NVMRC }}'

      - name: Set up dependencies
        run: npm ci

      - name: Build
        tabuses: ./.github/actions/build

      - name: Build docs
        run: npm run generateDocs

      - name: Commit and push changes
        run: |
            git config --global user.email "BOT_TonConnect_Builder@tonconnect.ton"
            git config --global user.name "BOT_TonConnect_Builder"
            git add -A
            git commit -m "build(docs): docs rebuild by github action"
            git push
